ARDUINO_COM_PORT = "COM4"
ARDUINO_SENDER_DELAY = 0.0
LOCATION = "sp"

CAMERA_PRIORITY = [1, 2]
LOG_PROJECT_ID = '682f7bbcb7063eb5d1bf92aa'

MIN_CALIBRATION_EXPOSURE = -10
MAX_CALIBRATION_EXPOSURE = -6
